version: '3.9'

networks:
  orbeon-network:
    name: orbeon_network

services:
  nginx:
    container_name: nginx-proxy
    image: nginx
    ports:
      - "4569:80"
    networks:
      - orbeon-network
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/logs:/var/log/nginx

  orbeon-wrapper:                        #it is just a name, which will be used only in this file.
    image: orbeon-wrapper             #name of the image after dockerfile executes
    container_name: orbeon-wrapper    #name of the container created from docker image
    build:
      context: .                          #docker file path (. means root directory)
      dockerfile: Dockerfile              #docker file name
    ports:
      - "9090:9090"                       #docker containter port with your os port
    restart: always
    networks:
      - orbeon-network
    depends_on:
      - orbeon-db
      - orbeon
      - nginx
    command: bash -c "./docker/run.sh"
    volumes:
      - ./:/usr/app
    environment:
      ENV: local
      PROFILE: local

  orbeon:
    build:
      context: ./orbeon
      dockerfile: Dockerfile
    image: orbeon
    container_name: orbeon
    ports:
      - "9091:9090"
    restart: always
    networks:
      - orbeon-network
    volumes:
      - ./orbeon:/opt/app
    depends_on:
      - orbeon-db
      - nginx
    command: bash -c "/opt/app/run.sh"
    environment:
      CATALINA_OPTS: "-Xms512M -Xmx1024M"
      API_URL: http://web:8000/api/v1

  orbeon-db:
    image: mysql:5.7
    restart: always
    container_name: orbeon-db
    ports:
      - "3308:3306"
    networks:
      - orbeon-network
    environment:
      MYSQL_ROOT_PASSWORD: test_password
      MYSQL_DATABASE: orbeon_db
      MYSQL_USER: test_username
      MYSQL_PASSWORD: test_password
    volumes:
      - ./mysql-data-orbeon:/var/lib/mysql
      - ./orbeon/sql:/opt/sql